export interface Dealer {
  name: string;
  city: string;
  address: string;
  email: string;
  website: string;
}

export const dealersList: Dealer[] = [
  { name: "Alfa Bike", address: "2030 Érd Bajcsy-Zsilinszky út 117.", city: "Érd", email: "info@alfabike.hu", website: "https://alfabike.hu" },
  { name: "Apacs Bike", address: "5310 Kisújszállás, Mikes utca 1.", city: "Kisújszállás", email: "info@apacsbike.hu", website: "https://apacsbike.hu/" },
  { name: "Apacs Bike", address: "5300 Karcag, Szent István sgt 4", city: "Karcag", email: "info@apacsbike.hu", website: "https://apacsbike.hu/" },
  { name: "Atomiclub", address: "1036 Budapest Galagonya u. 5.", city: "Budapest", email: "atomiclubalfa@gmail.com", website: "https://www.atomiclub.hu/" },
  { name: "B&Kero Kerékpárbolt", address: "4400 Nyíregyháza Debreceni út 130-132.", city: "Nyíregyháza", email: "bkero99@freemail.hu", website: "https://www.facebook.com/bandkero/" },
  { name: "Bakony Sport Kerékpárbolt", address: "8400 Ajka Petőfi Sándor utca 9-11", city: "Ajka", email: "bakonysport@gmail.com", website: "http://www.bakonysport.hu/" },
  { name: "Balázs Kerékpárbolt", address: "2000 Szentendre, Előd utca 2/a", city: "Szentendre", email: "balazskerekparboltok@gmail.com", website: "https://www.balazskerekparbolt.com/" },
  { name: "Berguson", address: "1035 Budapest Vihar utca 12.", city: "Budapest", email: "info@berguson.hu", website: "https://www.berguson.hu/" },
  { name: "Biciklikk", address: "7624 Pécs Kodály Zoltán utca 3.", city: "Pécs", email: "kerekpar.paylik@gmail.com", website: "https://www.biciklikk.hu/" },
  { name: "Biciklon Kerékpár Szaküzlet", address: "9700 Szombathely Paragvári utca 54.", city: "Szombathely", email: "Biciklon3@gmail.com", website: "http://www.biciklon.hu" },
  { name: "Biciklon Kerékpár Szaküzlet", address: "9900 Körmend Rákóczi u. 29.", city: "Körmend", email: "biciklon3@gmail.com", website: "http://www.biciklon.hu" },
  { name: "Bike Center", address: "8221 Balatonalmádi Szabolcs u. 17.", city: "Balatonalmádi", email: "bikecenterbalmadi@gmail.com", website: "https://www.facebook.com/p/Bike-center-Balatonalmádi-100057433608853/?locale=hu_HU" },
  { name: "Bike Shop Kerékpár", address: "6600 Szentes Új utca 13.", city: "Szentes", email: "bikeshop.motovent@gmail.com, ", website: "https://bikeshopszentes.hu/" },
  { name: "Bike System", address: "8174 Balatonkenese Vörösmarty tér 1.", city: "Balatonkenese", email: "info@bikesystem.hu", website: "https://bikesystem.hu/" },
  { name: "BikeNOW Kerékpár", address: "8600 Siófok Tanácsház u. 9.", city: "Siófok", email: "info@bikenow.hu", website: "https://www.bikenow.store" },
  { name: "Blaskovics Kerékpár", address: "9023 Győr Tihanyi Árpád út 58.", city: "Győr", email: "info@blaskovicskerekpar.hu", website: "http://www.blaskovicskerekpar.hu/" },
  { name: "Bombastic Kerékpárbolt", address: "3526 Miskolc Szentpéteri Kapu 80.", city: "Miskolc", email: "bombastic@bombastic.hu", website: "https://www.bombastic.hu/" },
  { name: "Böröcfi Kerékpárüzlet", address: "8600 Siófok Fő utca 99.", city: "Siófok", email: "pelsobikekft@gmail.com", website: "https://www.pelsobike.hu/" },
  { name: "Bringa Centrum", address: "6000 Kecskemét, Trombita utca 2.", city: "Kecskemét", email: "banojozsef@gmail.com", website: "https://bringabolt.com" },
  { name: "Bringa Szerviz", address: "3324 Felsőtárkány, Várhegy út 9.", city: "Felsőtárkány", email: "bringaberles@gmail.com", website: "https://www.facebook.com/felsotarkanybringa/?locale=hu_HU" },
  { name: "BringaBoard Kerékpár", address: "1135 Budapest Jász u.13.", city: "Budapest", email: "bringaboard@gmail.com", website: "https://bringaboard.hu/" },
  { name: "Bringavilág Kerékpárüzlet", address: "1078 Budapest Cserhát u 16-18", city: "Budapest", email: "info@bringavilag.com", website: "https://bringavilag.com/" },
  { name: "Canganyika Kerékpárüzlet", address: "5000 Szolnok Várkonyi tér 1.", city: "Szolnok", email: "canganyika21@gmail.com", website: "https://www.facebook.com/canganyika/?locale=hu_HU" },
  { name: "Centeer Bike Shop", address: "9200 Mosonmagyaróvár Flesch Károly utca 2", city: "Mosonmagyaróvár", email: "centlr.bike@gmail.com", website: "https://www.centeerbike.hu" },
  { name: "Csapesz Kerékpár", address: "4060 Balmazújváros, Kastély kert utca 7", city: "Balmazújváros", email: "csapeszkerekpar@t-online.hu", website: "https://csapesz.hu/" },
  { name: "Danabike Kerékpár Webáruház", address: "2360 Gyál Gábor Áron u. 29", city: "Gyál", email: "halasz.feri@gmail.com", website: "https://danabike.hu" },
  { name: "Eger Bike", address: "3300 Eger, Hadnagy út 17.", city: "Eger", email: "bolt@egerbike.hu", website: "https://egerbike.hu/" },
  { name: "Eurocikli Kerékpár", address: "7030 Paks Villany utca 2/B", city: "Paks", email: "blattko@gmail.com", website: "https://www.facebook.com/Eurocikli/" },
  { name: "Excelsior Sportcentrum", address: "3516 Miskolc, Pesti út 62.", city: "Miskolc", email: "excelsiormiskolc@gmail.com", website: "https://www.facebook.com/excelsiorsportcentrum/?locale=hu_HU" },
  { name: "Fertőd Bike", address: "9431 Fertőd Fő utca 22.", city: "Fertőd", email: "info@fertodbike.hu", website: "https://www.facebook.com/fertodbike/" },
  { name: "Fertőrákosi Kerékpárkölcsönző", address: "9421 Fertőrákos Fő utca 242.", city: "Fertőrákos", email: "webmester87@gmail.com", website: "" },
  { name: "Forum Sport", address: "8360 Keszthely Rákóczi u. 3.", city: "Keszthely", email: "forumsport@gmail.com", website: "https://www.facebook.com/keszthelykerekpar/?locale=hu_HU" },
  { name: "Galéria Kerékpárbolt", address: "7200 Dombóvár Kórház u. 42/B.", city: "Dombóvár", email: "szarkazoli71@gmail.com", website: "https://galeria-kerekparszakuzlet-es-szerviz.uzleti.hu/" },
  { name: "Györe Kerékpárkiállító", address: "2700 Cegléd, Kőrösi út 18.", city: "Cegléd", email: "info@gyorekerekpar.hu", website: "https://www.gyorekerekpar.hu/" },
  { name: "Gyula Bringa", address: "5700 Gyula Nagyváradi út 23.", city: "Gyula", email: "gyulabringa@gmail.com", website: "http://gyulabringa.hu/" },
  { name: "Hámorisport", address: "2013 Pomáz Kossuth Lajos utca 37.", city: "Pomáz", email: "hamorisport@gmail.com", website: "https://www.hamorisport.hu" },
  { name: "Heavy Pedal Kerékpár", address: "6723 Szeged Brüsszeli krt 12.", city: "Szeged", email: "heavypedal08@gmail.com", website: "https://heavypedal.hu/" },
  { name: "James Sport", address: "2600 Vác Oberlander tér 1.", city: "Vác", email: "szaszovszkyrobert@gmail.com", website: "" },
  { name: "Járműbolt", address: "9300, Csorna Erzsébet királyné u. 21.", city: "Csorna", email: "info@jarmuboltcsorna.hu", website: "https://jarmuboltcsorna.hu" },
  { name: "Jel Kerékpár Szaküzlet", address: "2800 Tatabánya, Kossuth Lajos út 101.", city: "Tatabánya", email: "jelkft@gmail.com", website: "https://www.facebook.com/Kerekparszakuzlet.jel/" },
  { name: "JóBringa Kerékpár Szaküzlet", address: "4032 Debrecen, Böszörményi út 153.", city: "Debrecen", email: "info@jobringa.hu", website: "https://www.jobringa.hu/" },
  { name: "Kerék Páros", address: "1094 Budapest Ferenc tér 9.", city: "Budapest", email: "pedalluskkft@gmail.com", website: "https://kerek-paros.hu/" },
  { name: "Kerékpár Diszkont", address: "8000 Székesfehérvár Lehel u. 30.", city: "Székesfehérvár", email: "kerekpardiszkont@gmail.com", website: "http://kerekpardiszkont.hu/" },
  { name: "Koffein Kerékpárműhely", address: "6795 Bordány Benke Gedeon u. 21", city: "Bordány", email: "koffeinkerekpar@gmail.com", website: "" },
  { name: "Körösi Kerékpárüzlet Bonyhád", address: "7150 Bonyhád Perczel Mór utca 36.", city: "Bonyhád", email: "korosiker@gmail.com", website: "" },
  { name: "Körösi Kerékpárüzlet Szekszárd", address: "7100 Szekszárd Széchenyi utca 55-57.", city: "Szekszárd", email: "kerekpar.korosi@gmail.com", website: "https://www.facebook.com/korosikerekpar/" },
  { name: "László Kerékpár", address: "1192 Budapest Határ út 30.", city: "Budapest", email: "laszlokerekpar11@gmail.com", website: "" },
  { name: "Local Bike Shop", address: "6000 Kecskemét, Dózsa György út 7.", city: "Kecskemét", email: "info@localbike.hu", website: "https://www.localbike.hu/" },
  { name: "Magellán Kerékpár centrum", address: "2400 Dunaújváros Szórád Márton út 6/A", city: "Dunaújváros", email: "magellanbt@gmail.com", website: "http://www.magellanbike.hu/" },
  { name: "Mango Bike Center", address: "9400 Sopron Lackner Kristóf utca 10.", city: "Sopron", email: "hallo@mangobike.hu", website: "https://www.mangobike.hu/" },
  { name: "Mátra Bike", address: "3200 Gyöngyös, Széchenyi út 7.", city: "Gyöngyös", email: "matrabike08@gmail.com", website: "https://www.facebook.com/p/Mátra-Bike-Kft-100063474095620/" },
  { name: "Merkl Kerékpár Gumi Szerviz", address: "2071 Páty, Rákóczi út 24.", city: "Páty", email: "merklbt@t-online.hu", website: "http://merkl.hu/" },
  { name: "Modul Bolt", address: "8053 Bodajk Petőfi u. 90.", city: "Bodajk", email: "info@modulbolt.hu", website: "https://www.modulbolt.hu/" },
  { name: "Mountain Béka Kerékpár", address: "2092 Budakeszi Táncsics Mihály u. 1.", city: "Budakeszi", email: "bringabolt@gmail.com", website: "https://m.facebook.com/Mountain-B" },
  { name: "Multi Motor és Bringa", address: "2370 Dabas Bartók Béla út 113.", city: "Dabas", email: "info@multi-bringa.hu", website: "https://www.multi-bringa.hu/" },
  { name: "Nelson Bike", address: "8200 Veszprém Almádi út 40", city: "Veszprém", email: "nelsonbike2012@gmail.com", website: "https://www.veszpremkerekpar.hu/" },
  { name: "Nor-Bike", address: "6100 Kiskunfélegyháza, Kalmár József utca 2.", city: "Kiskunfélegyháza", email: "norbike.tarsai@gmail.com", website: "https://webaruhaz.nor-bike.hu/" },
  { name: "Ottomax Kerékpár", address: "8060 Mór Deák Ferenc u. 32.", city: "Mór", email: "info@ottomax.hu", website: "https://www.morkerekpar.hu" },
  { name: "Pedál Kerékpárbolt", address: "3200 Gyöngyös Török Ignác utca 4.", city: "Gyöngyös", email: "gyongyos@pedalkerekpar.hu", website: "https://pedalkerekpar.hu/" },
  { name: "Pedál Kerékpárbolt", address: "3000 Hatvan, Kossuth tér 12.", city: "Hatvan", email: "pedalhatvan2@gmail.com", website: "https://pedalkerekpar.hu/" },
  { name: "Peppe Kerékpár", address: "9024 Győr Nagy Imre út 91.", city: "Győr", email: "info@peppekerekpar.hu", website: "https://peppekerekpar.hu/" },
  { name: "PNE Rodeó Kerékpár", address: "5000 Szolnok Pozsonyi út 12.", city: "Szolnok", email: "pnemobil@gmail.com", website: "https://pnemobilkft.hu/" },
  { name: "R Bike", address: "2900 Komárom Klapka György út 35.", city: "Komárom", email: "info@rbike.hu", website: "http://rbike.hu/" },
  { name: "Ráció 4Sport", address: "9700 Szombathely Farkas Károly utca 16.", city: "Szombathely", email: "protech10000@gmail.com", website: "https://4sport.hu/" },
  { name: "Rausch Kerékpárüzlet", address: "6500 Baja Czirfusz F. u. 4.", city: "Baja", email: "info@rauschkerekpar.hu", website: "https://rauschkerekpar.hu/" },
  { name: "Ride Bike", address: "1161 Budapest, Rákóczi utca 51.", city: "Budapest", email: "rakoczi@ridebike.hu", website: "https://ridebike.hu/" },
  { name: "Rimili Motor Kerékpár", address: "4700 Mátészalka Kölcsey Ferenc út 17/A", city: "Mátészalka", email: "zsolt.rimili@gmail.com", website: "https://rimoker.hu/" },
  { name: "Rompos Autósbolt Kerék Szerviz", address: "2651 Rétság, Korányi F utca 5.", city: "Rétság", email: "romposcsabi@gmail.com", website: "https://www.facebook.com/Rompos-Au" },
  { name: "Savaria Unikor Műszaki Áruház", address: "9700 Szombathely Mátyás Király u 26.", city: "Szombathely", email: "info@savariaunikor.hu", website: "https://savariaunikor.hu/" },
  { name: "Schmidt Járműbolt", address: "7700 Mohács Piac tér", city: "Mohács", email: "schmidtbt1997@freemail.hu", website: "https://www.facebook.com/schmidtjarmubolt/?locale=hu_HU" },
  { name: "SomoS Bike", address: "3360 Heves Rákóczi F. utca 31.", city: "Heves", email: "somosbikekft@gmail.com", website: "https://www.facebook.com/somosbikekft/?locale=hu_HU" },
  { name: "SomoS Bike", address: "3300 Eger Sas u. 29/a", city: "Eger", email: "somosbikekft@gmail.com", website: "https://www.facebook.com/somosbikekft/?locale=hu_HU" },
  { name: "Speedy Kerékpár", address: "5600 Békéscsaba, Gyóni Géza utca 22.", city: "Békéscsaba", email: "speedykerekpar@t-online.hu", website: "http://www.speedybicikli.hu/" },
  { name: "Sport 99 Kerékpár Sí üzlet", address: "2040 Budaörs, Budapesti út 99.", city: "Budaörs", email: "sport99budaors@gmail.com", website: "https://www.sport99.hu/" },
  { name: "Sportoázis", address: "8500 Pápa Külső- Veszprémi út 38", city: "Pápa", email: "info@sportoazis.hu", website: "https://www.facebook.com/sportoazis" },
  { name: "Sprint Kerékpárbolt", address: "5000 Szolnok, Baross utca 48.", city: "Szolnok", email: "andre.zsolt@gmail.com", website: "https://www.facebook.com/SprintKerekpar/" },
  { name: "Stop-Shop Kerékpár", address: "3700 Kazincbarcika Csokonai utca 30.", city: "Kazincbarcika", email: "stop2000bt@gmail.com", website: "" },
  { name: "Szegi Sport", address: "8253 Révfülöp Csárda u.1", city: "Révfülöp", email: "szegijanos@gmail.com", website: "http://www.szegi-sport.hu/" },
  { name: "Tarján Sport", address: "2831 Tarján Móricz Zsigmond tér 3.", city: "Tarján", email: "tarjansport@gmail.com", website: "http://www.tarjansport.hu/" },
  { name: "Tempo Kerékpár Üzlet", address: "8230 Balatonfüred Ady E u 52", city: "Balatonfüred", email: "kerekpar.tempo@gmail.com", website: "https://tempokerekpar.hu/" },
  { name: "TI-BIKE Kerékpárüzlet és Szerviz", address: "4060 Balmazújváros Veres Péter u. 7.", city: "Balmazújváros", email: "info@ti-bike.hu", website: "https://www.facebook.com/TiBikeBalmaz/?locale=hu_HU" },
  { name: "Titó Bike Shop", address: "2760 Nagykáta Szabadság tér 7.", city: "Nagykáta", email: "minarovics78@gmail.com", website: "" },
  { name: "Tóparti Kerékpár", address: "2890 Tata Május 1. u. 5.", city: "Tata", email: "topartikerekpar@gmail.com", website: "https://www.facebook.com/p/Tóparti-Kerékpárbolt-100057490688083/" },
  { name: "Tutti Bringa", address: "7400 Kaposvár, Vásártéri utca 17.", city: "Kaposvár", email: "info@tuttibringa.hu", website: "https://www.tuttibringa.hu/" },
  { name: "Uno Autó-Motor-Kerékpár", address: "9200 Mosonmagyaróvár Liszt F u 4.", city: "Mosonmagyaróvár", email: "info@unoautomotor.hu", website: "http://unoautomotor.hu/" },
  { name: "Vadon Sport Sí Kerékpár", address: "1117 Budapest, Október huszonharmadika", city: "Budapest", email: "info@vadonsport.hu", website: "https://www.vadonsport.hu/" },
  { name: "Véka Sport", address: "8638 Balatonlelle Rákóczi út 230.", city: "Balatonlelle", email: "vekasport@gmail.com", website: "https://www.facebook.com/VekaSport/" },
  { name: "Velence Bike", address: "2481 Velence, Fő utca 172.", city: "Velence", email: "info@velencebike.hu", website: "http://tosport.hu/" },
  { name: "Velo Sport Kerékpárüzlet", address: "3100 Salgótarján Füleki út 8.", city: "Salgótarján", email: "info@velosport.hu", website: "http://velosport.hu/" },
  { name: "Viktor Motor Shop", address: "6200 Kiskőrös Dózsa Gy. u.17.", city: "Kiskőrös", email: "info@viktormotor.hu", website: "http://viktormotor.hu/" },
  { name: "Winkler Sport", address: "2120 Dunakeszi Fő utca 85.", city: "Dunakeszi", email: "info@winklersport.hu", website: "https://www.winklersport.hu/" },
  { name: "Yanko's Kerékpár Szaküzlet", address: "8800 Nagykanizsa Zrínyi Miklós utca 11.", city: "Nagykanizsa", email: "ferenc.jankovics@gmail.com", website: "https://yankosbike.hu/" },
  { name: "Zoli Kerékpár", address: "2534 Tát, Árpád utca 22.", city: "Tát", email: "bolt@zolikerekpar.hu", website: "https://www.zolikerekpar.hu/" }
];
