export interface Dealer {
  city: string;
  name: string;
  address: string;
  email: string;
  website: string;
}

export const normalizeCity = (city: string) =>
  city
    .trim()
    .toLocaleLowerCase('hu-HU')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

export const dealersList: Dealer[] = [
  { city: 'Érd', name: 'Alfa Bike', address: '2030 Érd Bajcsy-Zsilinszky út 117.', email: 'info@alfabike.hu', website: 'https://alfabike.hu' },
  { city: 'Kisújszállás', name: 'Apacs Bike', address: '5310 Kisújszállás, Mikes utca 1.', email: 'info@apacsbike.hu', website: 'https://apacsbike.hu/' },
  { city: 'Karcag', name: 'Apacs Bike', address: '5300 Karcag, Szent István sgt 4', email: 'info@apacsbike.hu', website: 'https://apacsbike.hu/' },
  { city: 'Püspökladány', name: 'Apacs Bike', address: '4150 Püspökladány, Hősök tere 5.', email: 'info@apacsbike.hu', website: 'https://apacsbike.hu/' },
  { city: 'Hajdúszoboszló', name: 'Apacs Bike', address: '4200 Hajdúszoboszló Szilfákalja u. 10-12.', email: 'info@apacsbike.hu', website: 'https://apacsbike.hu/' },
  { city: 'Budapest', name: 'Atomiclub', address: '1036 Budapest Galagonya u. 5.', email: 'atomiclubalfa@gmail.com', website: 'https://www.atomiclub.hu/' },
  { city: 'Nyíregyháza', name: 'B&Kero Kerékpárbolt', address: '4400 Nyíregyháza Debreceni út 130-132.', email: 'bkero99@freemail.hu', website: 'https://www.facebook.com/bandkero/' },
  { city: 'Ajka', name: 'Bakony Sport Kerékpárbolt', address: '8400 Ajka Petőfi Sándor utca 9-11', email: 'bakonysport@gmail.com', website: 'http://www.bakonysport.hu/' },
  { city: 'Szentendre', name: 'Balázs Kerékpárbolt', address: '2000 Szentendre, Előd utca 2/a', email: 'balaszkerparboltok@gmail.com', website: 'http://www.balazskerekparbolt.com/' },
  { city: 'Budapest', name: 'Berguson', address: '1035 Budapest Vihar utca 12.', email: 'info@berguson.hu', website: 'https://www.berguson.hu/' },
  { city: 'Pécs', name: 'Biciklikk', address: '7624 Pécs Kodály Zoltán utca 3.', email: 'kerekpar.pavlik@gmail.com', website: 'https://www.biciklikk.hu/' },
  { city: 'Szombathely', name: 'Biciklon Kerékpár Szaküzlet', address: '9700 Szombathely Paragvári utca 54.', email: 'Biciklon3@gmail.com', website: 'http://www.biciklon.hu' },
  { city: 'Körmend', name: 'Biciklon Kerékpár Szaküzlet', address: '9900 Körmend Rákóczi u. 29.', email: 'Biciklon3@gmail.com', website: 'http://www.biciklon.hu' },
  { city: 'Balatonalmádi', name: 'Bike Center', address: '8221 Balatonalmádi Szabolcs u. 17.', email: 'bikecenterbalmadi@gmail.com', website: 'https://www.facebook.com/p/Bike-center-Balatonalmádi-100057436088885/' },
  { city: 'Szentes', name: 'Bike Shop Kerékpár', address: '6600 Szentes Új utca 13.', email: 'bikeshop.motovent@gmail.com', website: 'https://bikeshopszentes.hu' },
  { city: 'Balatonkenese', name: 'Bike System', address: '8174 Balatonkenese Vörösmarty tér 1.', email: 'info@bikesystem.hu', website: 'https://bikesystem.hu' },
  { city: 'Siófok', name: 'BikeNOW Kerékpár', address: '8600 Siófok Tanácsházi u. 9.', email: 'info@bikenow.hu', website: 'https://www.bikenow.store' },
  { city: 'Győr', name: 'Blaskovics Kerékpár', address: '9023 Győr Tihanyi Árpád út 58.', email: 'info@blaskovicskerekpar.hu', website: 'http://www.blaskovicskerekpar.hu/' },
  { city: 'Miskolc', name: 'Bombastic Kerékpárbolt', address: '3526 Miskolc Szentpéteri Kapu 80.', email: 'bombastic@bombastic.hu', website: 'https://www.bombastic.hu/' },
  { city: 'Siófok', name: 'Böröcfi Kerékpárüzlet', address: '8600 Siófok Fő utca 99.', email: 'pelsobikekft@gmail.com', website: 'https://www.pelsobike.hu' },
  { city: 'Kecskemét', name: 'Bringa Centrum', address: '6000 Kecskemét, Trombita utca 2.', email: 'banojozsef@gmail.com', website: 'https://bringabolt.com' },
  { city: 'Felsőtárkány', name: 'Bringa Szerviz', address: '3324 Felsőtárkány, Várhegy út 9.', email: 'bringaberles@gmail.com', website: 'https://www.facebook.com/felsotarkanybringa/' },
  { city: 'Budapest', name: 'BringaBoard Kerékpár', address: '1135 Budapest Jász u.13.', email: 'bringaboard@gmail.com', website: 'https://www.bringaboard.hu/' },
  { city: 'Budapest', name: 'Bringavilág Kerékpárüzlet', address: '1078 Budapest Cserháti u. 16-18.', email: 'info@bringavilag.com', website: 'https://www.bringavilag.com/' },
  { city: 'Szolnok', name: 'Canganyika Kerékpárüzlet', address: '5000 Szolnok Várkonyi tér 1.', email: 'canganyika21@gmail.com', website: 'https://www.facebook.com/canganyika/' },
  { city: 'Mosonmagyaróvár', name: 'Centeer Bike Shop', address: '9200 Mosonmagyaróvár Flesch Károly utca', email: 'centir.bike@gmail.com', website: 'https://www.centeerbike.hu' },
  { city: 'Balmazújváros', name: 'Csapesz Kerékpár', address: '4060 Balmazújváros, Kastély kert utca 7', email: 'csapeszkerekpar@t-online.hu', website: 'https://csapesz.hu' },
  { city: 'Gyál', name: 'Danabike Kerékpár Webáruház', address: '2360 Gyál Gábor Áron u. 29', email: 'halasz.ferl@gmail.com', website: 'https://danabike.hu' },
  { city: 'Eger', name: 'Eger Bike', address: '3300 Eger, Hadnagy utca 17.', email: 'bolt@egerbike.hu', website: 'https://egerbike.hu' },
  { city: 'Paks', name: 'Eurocikli Kerékpár', address: '7030 Paks Villany utca 2/B', email: 'blattko@gmail.com', website: 'https://www.facebook.com/Eurocikli/' },
  { city: 'Miskolc', name: 'Excelsior Sportcentrum', address: '3516 Miskolc, Pesti út 62.', email: 'excelsiormiskolc@gmail.com', website: 'https://www.facebook.com/excelsiorsportcentrum/' },
  { city: 'Fertőd', name: 'Fertőd Bike', address: '9431 Fertőd Fő utca 22.', email: 'fertodbike@gmail.com', website: 'https://www.facebook.com/fertodbike/' },
  { city: 'Fertőrákos', name: 'Fertőrákosi Kerékpárkölcsönző', address: '9421 Fertőrákos Fő utca 242.', email: 'webmester87@gmail.com', website: '' },
  { city: 'Keszthely', name: 'Forum Sport', address: '8360 Keszthely Rákóczi u. 3.', email: 'forumspoort@gmail.com', website: 'https://www.facebook.com/keszthelykerekpar/' },
  { city: 'Dombóvár', name: 'Galéria Kerékpárbolt', address: '7200 Dombóvár Kórház u. 42/B.', email: 'szarkazol721@gmail.com', website: 'https://galeria-kerekparszakuzlet.es-szerviz.uzleti.hu/' },
  { city: 'Cegléd', name: 'Győre Kerékpáristálló', address: '2700 Cegléd, Kőrösi út 18.', email: 'info@gyorekerekpar.hu', website: 'https://www.gyorekerekpar.hu/' },
  { city: 'Gyula', name: 'Gyula Bringa', address: '5700 Gyula Nagyváradi út 23.', email: 'gyulabringa@gmail.com', website: 'http://www.gyulabringa.com/' },
  { city: 'Pomáz', name: 'Hámorisport', address: '2013 Pomáz Kossuth Lajos utca 37.', email: 'hamorisport@gmail.com', website: 'http://www.hamorisport.hu' },
  { city: 'Szeged', name: 'Heavy Pedal Kerékpár', address: '6723 Szeged Brüsszeli krt 12.', email: 'heavypedal08@gmail.com', website: 'http://www.heavypedal.hu/' },
  { city: 'Vác', name: 'James Sport', address: '2600 Vác Oberlander tér 1.', email: 'szaszovszkyrobert@gmail.com', website: '' },
  { city: 'Csorna', name: 'Jármübolt', address: '9300 Csorna Erzsébet királyné u. 21.', email: 'info@jarmuboltcsorna.hu', website: 'https://jarmuboltcsorna.hu/' },
  { city: 'Tatabánya', name: 'Jel Kerékpár Szaküzlet', address: '2800 Tatabánya, Kossuth Lajos út 101.', email: 'jelkft@gmail.com', website: 'https://www.facebook.com/kerekparszakuzlet.jel/' },
  { city: 'Debrecen', name: 'JóBringa Kerékpár Szaküzlet', address: '4032 Debrecen, Böszörményi út 153.', email: 'info@jobringa.hu', website: 'https://www.jobringa.hu/' },
  { city: 'Budapest', name: 'Kerék Páros', address: '1094 Budapest Ferenc tér 9.', email: 'pedalluskft@gmail.com', website: 'https://kerek-paros.hu' },
  { city: 'Székesfehérvár', name: 'Kerékpár Diszkont', address: '8000 Székesfehérvár Lehel u. 30.', email: 'info@kerekpardiszkont.hu', website: 'http://www.kerekpardiszkont.hu/' },
  { city: 'Bordány', name: 'Koffein Kerékpárműhely', address: '6795 Bordány Benke Gedeon u. 21.', email: 'koffeinkerekpar@gmail.com', website: '' },
  { city: 'Bonyhád', name: 'Körösi Kerékpárüzlet Bonyhád', address: '7150 Bonyhád Perczel Mór utca 36.', email: 'korosiker@gmail.com', website: '' },
  { city: 'Szekszárd', name: 'Körösi Kerékpárüzlet Szekszárd', address: '7100 Szekszárd Széchenyi utca 55-57.', email: 'kerekpar.korosi@gmail.com', website: 'https://www.facebook.com/korosikerekpar/' },
  { city: 'Budapest', name: 'László Kerékpár', address: '1192 Budapest Határ út 30.', email: 'laszlokerekpar11@gmail.com', website: '' },
  { city: 'Kecskemét', name: 'Local Bike Shop', address: '6000 Kecskemét, Dózsa György út 7.', email: 'info@localbike.hu', website: 'https://www.localbike.hu/' },
  { city: 'Dunaújváros', name: 'Magellán Kerékpár Centrum', address: '2400 Dunaújváros Sórádi mátron út 6/A', email: 'magellanbt@gmail.com', website: 'http://www.magellanbt.hu/' },
  { city: 'Sopron', name: 'Mango Bike Center', address: '9400 Sopron Lackner Kristóf utca 10', email: 'hallo@mangobike.hu', website: 'https://www.mangobike.hu/' },
  { city: 'Gyöngyös', name: 'Mátra Bike', address: '3200 Gyöngyös, Széchenyi út 2.', email: 'matrabike08@gmail.com', website: 'https://www.facebook.com/p/Mátra-Bike-Kft-100063474095620/' },
  { city: 'Páty', name: 'Merkl Kerékpár Gumi Szerviz', address: '2071 Páty, Rákóczi út 24.', email: 'merklbt@t-online.hu', website: 'http://www.merkl.hu/' },
  { city: 'Bodajk', name: 'Modul Bolt', address: '8053 Bodajk Petőfi u.90.', email: 'info@modulbolt.hu', website: 'http://www.modulbolt.hu/' },
  { city: 'Budakeszi', name: 'Mountain Béka Kerékpár', address: '2092 Budakeszi Táncsics Mihály u. 1.', email: 'bringabolt@gmail.com', website: 'https://m.facebook.com/Mountain-Beka-Kerekpar/' },
  { city: 'Dabas', name: 'Multi-Motor és Bringa', address: '2370 Dabas Bartók Béla út. 113.', email: 'info@multi-bringa.hu', website: 'https://www.multi-bringa.hu/' },
  { city: 'Veszprém', name: 'Nelson Bike', address: '8200 Veszprém Almádi út 40', email: 'nelsonbike2012@gmail.com', website: 'https://www.veszpremkerekpar.hu/' },
  { city: 'Kiskunfélegyháza', name: 'Nor-Bike', address: '6100 Kiskunfélegyháza, Kalmár József utca', email: 'norbike.tarsai@gmail.com', website: 'https://webaruhaz.nor-bike.hu/' },
  { city: 'Mezőkövesd', name: 'Ódor Kerékvár', address: '3400 Mezőkövesd Mátyás király utca 58.', email: 'odorkerekvar@gmail.com', website: 'https://www.facebook.com/odorkerekvar.hu' },
  { city: 'Mór', name: 'Ottomax Kerékpár', address: '8060 Mór Deák Ferenc u. 32.', email: 'info@ottomax.hu', website: 'http://www.morkerekpar.hu/' },
  { city: 'Gyöngyös', name: 'Pedál Kerékpárbolt', address: '3200 Gyöngyös Török Ignác utca 4.', email: 'gyongyos@pedalkerekpar.hu', website: 'https://pedalkerekpar.hu/' },
  { city: 'Hatvan', name: 'Pedál Kerékpárbolt', address: '3000 Hatvan, Széchenyi tér 12.', email: 'pedalhatvan2@gmail.com', website: 'https://www.pedalkerekpar.hu/' },
  { city: 'Győr', name: 'Peppe Kerékpár', address: '9024 Győr Nagy Imre út 91.', email: 'info@peppekerekpar.hu', website: 'https://www.peppekerekpar.hu/' },
  { city: 'Szolnok', name: 'PNE Rodeó Kerékpár', address: '5000 Szolnok Pozsonyi út 13.', email: 'pnemobil@gmail.com', website: 'http://www.pnemobilkft.hu/' },
  { city: 'Komárom', name: 'R Bike', address: '2900 Komárom Klapka György út 35.', email: 'info@rbike.hu', website: '' },
  { city: 'Szombathely', name: 'Rácio 4Sport', address: '9700 Szombathely Farkas Károly utca 16.', email: 'protech10000@gmail.com', website: 'https://4sport.hu' },
  { city: 'Baja', name: 'Rausch Kerékpárüzlet', address: '6500 Baja Czirfusz F. u. 4.', email: 'info@rauschkerekpar.hu', website: 'https://rauschkerekpar.hu' },
  { city: 'Budapest', name: 'Ride Bike', address: '1161 Budapest, Rákóczi utca 51.', email: 'rakoczi@ridebike.hu', website: 'https://ridebike.hu' },
  { city: 'Mátészalka', name: 'Rimili Motor Kerékpár', address: '4700 Mátészalka Kölcsey Ferenc utca 17/A', email: 'zsolt.rimili@gmail.com', website: 'https://rimoker.hu' },
  { city: 'Rétság', name: 'Rompos Autósbolt Kerékpár S.', address: '2651 Rétság, Korányi F utca 5.', email: 'romposcsabi@gmail.com', website: 'https://www.facebook.com/Rompos-Autobolt/' },
  { city: 'Szombathely', name: 'Savaria Uniker Műszaki Áruház', address: '9700 Szombathely Királyfi Király u. 26.', email: 'info@savariauniker.hu', website: '' },
  { city: 'Mohács', name: 'Schmidt Jármübolt', address: '7700 Mohács Piac tér', email: 'schmidtbt1997@freemail.hu', website: 'https://www.facebook.com/schmidtjarmubolt/' },
  { city: 'Heves', name: 'SomoS Bike', address: '3360 Heves Rákóczi F. utca 31.', email: 'somosbikekft@gmail.com', website: 'https://www.facebook.com/somosbikekft/' },
  { city: 'Eger', name: 'SomoS Bike', address: '3300 Eger Sas u. 29/a', email: 'somosbikekft@gmail.com', website: 'https://www.facebook.com/somosbikekft/' },
  { city: 'Békéscsaba', name: 'Speedy Kerékpár', address: '5600 Békéscsaba Gyóni Géza utca 22.', email: 'speedykerekpar@t-online.hu', website: 'https://www.speedybicikli.hu/' },
  { city: 'Budaörs', name: 'Sport 99 Kerékpár Si Üzlet', address: '2040 Budaörs, Budapesti út 99.', email: 'sport99budaors@gmail.com', website: 'http://www.sport99.hu/' },
  { city: 'Pápa', name: 'Sportoázis', address: '8500 Pápa Külső-Veszprémi út. 38', email: 'info@sportoazis.hu', website: 'https://www.facebook.com/sportoazis' },
  { city: 'Szolnok', name: 'Sprint Kerékpárbolt', address: '5000 Szolnok, Baross utca 48.', email: 'andre.zsolt@gmail.com', website: 'https://www.facebook.com/SprintKerekpar/' },
  { city: 'Kazincbarcika', name: 'Stop-Shop Kerékpár', address: '3700 Kazincbarcika Csokonai utca 30.', email: 'stop2000bt@gmail.com', website: '' },
  { city: 'Révfülöp', name: 'Szegi Sport', address: '8253 Révfülöp Csárda u.1', email: 'szegijanos@gmail.com', website: 'http://www.szegi-sport.hu/' },
  { city: 'Tarján', name: 'Tarján Sport', address: '2831 Tarján Móricz Zsigmond tér 3.', email: 'tarjansport@gmail.com', website: 'http://www.tarjansport.hu/' },
  { city: 'Balatonfüred', name: 'Tempo Kerékpár Üzlet', address: '8230 Balatonfüred Ady E u 52', email: 'kerekpar.tempo@gmail.com', website: 'https://tempokerekpar.hu/' },
  { city: 'Balmazújváros', name: 'TI-BIKE Kerékpárüzlet és Szerviz', address: '4060 Balmazújváros Veres Péter u. 7.', email: 'info@ti-bike.hu', website: 'https://www.facebook.com/TiBikeBalmaz/' },
  { city: 'Nagykáta', name: 'Titó Bike Shop', address: '2760 Nagykáta Szabadság tér 7.', email: 'minarovics78@gmail.com', website: '' },
  { city: 'Tata', name: 'Tóparti Kerékpár', address: '2890 Tata Május 1. u. 5.', email: 'info@topartikerekpar.hu', website: 'https://www.facebook.com/p/Tóparti-Kerékpárbolt-100057490688083/' },
  { city: 'Kaposvár', name: 'Tutti Bringa', address: '7400 Kaposvár, Vásártéri utca 17.', email: 'info@tuttibringa.hu', website: 'https://www.tuttibringa.hu/' },
  { city: 'Mosonmagyaróvár', name: 'Uno Autó-Motor-Kerékpár', address: '9200 Mosonmagyaróvár Liszt F u 4.', email: 'info@unoautomotor.hu', website: '' },
  { city: 'Budapest', name: 'Vadon Sport Si Kerékpár', address: '1117 Budapest, Október huszonharmadika utca', email: 'info@vadonsport.hu', website: 'https://www.vadonsport.hu/' },
  { city: 'Balatonlelle', name: 'Véka Sport', address: '8638 Balatonlelle Rákóczi út 230.', email: 'vekasport@gmail.com', website: '' },
  { city: 'Velence', name: 'Velence Bike', address: '2481 Velence, Fő utca 172.', email: 'info@velencebike.hu', website: 'http://tosport.hu/' },
  { city: 'Salgótarján', name: 'Velo Sport Kerékpárüzlet', address: '3100 Salgótarján Füleki út 8.', email: 'info@velosport.hu', website: 'http://www.velosport.hu/' },
  { city: 'Kiskőrös', name: 'Viktor Motor Shop', address: '6200 Kiskőrös Dózsa Gy. u.17.', email: 'info@viktormotor.hu', website: '' },
  { city: 'Dunakeszi', name: 'Winkler Sport', address: '2120 Dunakeszi Fő utca 85.', email: 'info@winklersport.hu', website: 'https://www.winklersport.hu/' },
  { city: 'Nagykanizsa', name: "Yanko's Kerékpár Szaküzlet", address: '8800 Nagykanizsa Zrínyi Miklós utca 11.', email: 'ferenc.jankovics@gmail.com', website: 'http://www.yankosbike.hu' },
  { city: 'Tát', name: 'Zoli Kerékpár', address: '2534 Tát, Árpád utca 22.', email: 'bolt@zolikerekpar.hu', website: '' },
];
